# Generated by Django 5.0 on 2024-01-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_game_file_alter_game_image_gamedevrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
