# Generated by Django 5.0 on 2024-01-04 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_game_average_rating_alter_game_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_games', through='posts.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_members',
            field=models.ManyToManyField(related_name='developed_games', through='posts.GameDevRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
