# Generated by Django 4.2.9 on 2024-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_game_ratings_alter_game_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visit_time'],
                'indexes': [models.Index(fields=['-visit_time'], name='posts_sitev_visit_t_1c5b35_idx')],
            },
        ),
    ]
