# Generated by Django 4.2.9 on 2024-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_sitevisittracker_visit_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisittracker",
            name="location",
            field=models.CharField(default="", max_length=50),
        ),
    ]
