# Generated by Django 4.2.9 on 2025-05-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_sitevisittracker_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisitTrackerVisitedPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visited_paths",
                        to="posts.sitevisittracker",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "ip"],
                "indexes": [
                    models.Index(fields=["ip"], name="posts_sitev_ip_id_bac19f_idx")
                ],
            },
        ),
    ]
