# Generated by Django 4.2.9 on 2024-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitation_invitee_username_invitation_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitee_username',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
